### ISSUE TITLE
sampleRasterStackByMU - generalizations

### ISSUE THREAD

**Issue by brownag** [ncss-tech/sharpshootR#23]
Just a few simple things I noticed about `sampleRasterStackByMU` that are probably worth fixing

---

Add required argument to specify polygon.id column. Or auto-calculate a column called 'pID'

```
#...
    suppressMessages(s <- constantDensitySampling(mu.i.sp, 
      n.pts.per.ac = pts.per.acre, min.samples = 1, polygon.id = "pID", 
      iterations = 20))
#...
```

Column names (quantiles) for polygon summary of musym are hard-coded. Even though the requested quantiles/probability levels `p` are allowed to vary. 

Either make `p` hardcoded as `p <-c(0,0.05,0.25,0.5,0.75,0.95,1)` or come up with routine for custom naming of columns.

```
.quantiles <- quantile(a, probs = p)
a.stats <- c(round(c(.quantiles, .total.area, .samples, 
        .polygons, .unsampled.polygons)), .mean.sample.density)
names(a.stats) <- c("Min", "Q5", "Q25", "Median", 
        "Q75", "Q95", "Max", "Total Area", "Samples", 
        "Polygons", "Polygons Not Sampled", "Mean Sample Dens.")
```

Polygon spelled wrong in column name of validity result
```
  validity.res <- data.frame(id = mu[[mu.col]], Plolygon.Validity = rgeos::gIsValid(mu, 
    byid = TRUE, reason = TRUE), stringsAsFactors = FALSE)
```

**Comment by dylanbeaudette** [comment]
All worth fixing. Testing can be done via MU comparison report. I don't know of many other places where this function is routinely used. Thanks for flagging these things for fixes.

**Comment by brownag** [comment]
Done and tested with MU comparison report v3.3.9.
