### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/sharpshootR#29]
Plan is to make a CRAN release of sharpshootR 1.6.6 soon (before Stats class)

 - [ ] Run spellcheck on docs
 - [ ] Rebuild HTML docs
 - [ ] Update NEWS

Anyone feel free to comment or add to above list.

**Comment by brownag** [comment]
This was a revdep converted to worse in the latest release 2.5.9; resolved in https://github.com/ncss-tech/sharpshootR/commit/354860fa439a37de97ddefcb7909359e9825cbe6; told CRAN folks that we would have 1.6.6 sorted out soon, and they sent soilDB on its way.

```
Package: sharpshootR
Check: tests
New result: ERROR
    Running â€˜testthat.Râ€™ [4s/5s]
  Running the tests in â€˜tests/testthat.Râ€™ failed.
  Complete output:
    > library(testthat)
    > library(sharpshootR)
    > 
    > test_check("sharpshootR")
    â•â• Failed tests â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    â”€â”€ Error (test-multinominal2logical.R:14:1): (code run outside of `test_that()`) â”€â”€
    Error: `v` must be a factor
    Backtrace:
        â–ˆ
     1. â””â”€sharpshootR::multinominal2logical(loafercreek, "hillslopeprof") test-multinominal2logical.R:14:0
    
    [ FAIL 1 | WARN 0 | SKIP 0 | PASS 24 ]
    Error: Test failures
    Execution halted
```

**Comment by dylanbeaudette** [comment]
Thanks for letting me know. I made `multinominal2logical` less strict, and we should be good to go. Shipping off to CRAN after we sort out the remaining PRs.
