### ISSUE TITLE
Add in Northing and Easting functionality to PLSS2LL

### ISSUE THREAD

**Issue by MollicMeyer** [ncss-tech/sharpshootR#56]
#53 

Hello, this is in reference to `formatPLSS` and `PLSS2LL`

We're working with a lot of legacy data where the location description in it's entirety is simlar to:

" 2400ft. N and 1540ft. W of SE corner of section 28, T100N R4W," for site 1-41B-1

Which is simple enough for the Township Range Section and 'corner' in this case, although the corner refers to the quarter of the quarter (qq) so we would have a formatted dataframe as such : `data.frame('id' = '1-41B-1', 'qq', = 'SE' 'q' = 'SE', 's' = 28, 't' = 'T100N', 'r' ='R4W', 'type' = ?, 'm' = ??)`

But it would be valuable to add a nudge factor for the proverbial "easting" and "northing", foot distances, so once the latlong was calculated down to the the quarter or the quarter of the quarter, the site could be bumped 2400 ft N and -1540 feet east?

Also, is the latlong calcuated at the center of the most precise information? if only the section number was given, would it be the center of the section? 

Thank you,
Meyer

**Comment by amclean1917** [comment]
holy cow - i came here to ask this same question. historical well logs are a treat, huh?

as far as ive been able to determine, at present the LL does not actually factor in q/qq, so it's a touch puzzling as to why it permits it. this can likely be done manually by simply finding the midpoints of the bounds (xmin, xmax, ymin, ymax) which you'll see the code produces when doing LL2PLSS and then the midpoints of the newly generated quadrants.  to manipulate by feet you'd probably have to convert those feet measurements to dd or ll and from there it'd just be addition/subtraction from the midpoint. 

the problem im running into is I can't actually fetch the xmax, xmin, ymax, and ymin that the code references. ill keep posting if i get to the solution, but was so floored by the concidence of you posting my question within minutes of me coming here, i had to comment :~)

**Comment by amclean1917** [comment]
also FYI - for 'type', set that equal to 'SN' (standard) and for 'm', thats the meridian you're referencing, since TRS repeats across the country. I'm in the PNW, so it's OR33 or the wilammete meridian.

**Comment by brownag** [comment]
> But it would be valuable to add a nudge factor for the proverbial "easting" and "northing", foot distances, so once the latlong was calculated down to the the quarter or the quarter of the quarter, the site could be bumped 2400 ft N and -1540 feet east?

Currently we take whatever the BLM API gives back as a centroid.  I agree this would be valuable, but I am not going to implement it. I would rather not have to bring in projection to another system etc. Right now it gives back exactly what the API returns. Perhaps one of the other contributors would be interested in taking this on, or one of you want to submit a pull request.

While it might work fine for the cases where the offsets are given relative to standard corners, that is not always the case and I feel that these methods are already a bit too complicated. Most of my workflows that use this tool use the centroid locations as a first approximation that is then customized manually based on the rest of the narrative description and other site characteristics.

> as far as ive been able to determine, at present the LL does not actually factor in q/qq, so it's a touch puzzling as to why it permits it.

Not quite. See below.

> Also, is the latlong calcuated at the center of the most precise information? if only the section number was given, would it be the center of the section?

Yes, generally the BLM API will return the quarter-quarter section if specified to that level. The points are the centroids at the quarter-quarter, section, or township level. In some instances you will find the centroid you get is at a less-detailed level of the PLSS hierarchy. I don't know why this is, and the API seems to silently do this without any indication of error or bad input. This is not all locations, but possibly has something to do with protracted boundaries, unsurveyed areas etc. Generally these problem points do occur in areas that are now sectionized.

**Comment by dylanbeaudette** [comment]
Thanks @brownag, I agree that adding additional complexity to this function (especially projection to local, planar CRS) is beyond the current scope. Most of the use cases (thus far) have focused on the section and section aliquot (q, qq) centroids. Now, it might be possible to add an argument for returning labeled corner points vs. centroids. I'll have to look at the API / function code to determine that.

Beyond that, you will likely need to use `PLSS2LL()` within a more specialized function or work-flow so that it can solve these specific problems. Over a decade ago, I recall doing something like this, working directly with the PLSS fabric for easy access to the PLSS geometry. You can probably find those data split to qq-section online somewhere.

**Comment by MollicMeyer** [comment]
That is pretty ironic @amclean1917 and thank you for the tips! And thank you @brownag and @dylanbeaudette for elaborating on why this would just further complicate things. I appreciate you looking into it. It shouldn't be an issue for me to set up some custom codes for more specific coordinates, I just thought it would maybe be useful for others since it's a rather prevalent problem.

**Comment by brownag** [comment]
@MollicMeyer  I think that potentially you could do `PLSS2LL()` to get centroid and then `LL2PLSS()` on the centroid(s) to get the PLSS geometries, which then you can then manipulate as needed. At least for the section or quarter-quarter section level. @amclean1917 this may be what you were alluding to.

This is a bit circuitous, but technically gets what you want, and prevents you needing a local copy of the PLSS geometry. From result you could calculate corners or any other characteristics from that geometry.

``` r
library(sharpshootR)
d <- data.frame(id = 1:6, plssid = formatPLSS(data.frame(
  id = 1:6,
  qq = c("", "", "NE", "NW", "SE", "SW"),
  q = c("", "", "NE", "NE", "NE", "NE"),
  s = c("", 11, 11, 11, 11, 11), 
  t = "T25S",
  r = "R38E",
  type = "SN",
  m = "CA21",
  stringsAsFactors = FALSE
)))
#> Dropping quarter and quarter-quarter sections due to bad formatting: 
#> Dropping quarter and quarter-quarter sections due to bad formatting:

# center of township, center of section
# center of NE,NW,SE,SW corner of northeast corner
p <- PLSS2LL(d)
v <- LL2PLSS(p$lon, p$lat)
plot(v$geom)
plot(sf::st_as_sf(p, coords = c("lon", "lat"), crs = "OGC:CRS84"), add = TRUE)
```

![](https://i.imgur.com/sECGBjh.png)

``` r
lapply(v$geom, sf::st_bbox)
#> [[1]]
#>       xmin       ymin       xmax       ymax 
#> -117.88384   35.75081 -117.87936   35.75448 
#> 
#> [[2]]
#>      xmin      ymin      xmax      ymax 
#> -117.8572   35.7763 -117.8527   35.7800 
#> 
#> [[3]]
#>       xmin       ymin       xmax       ymax 
#> -117.85273   35.77997 -117.84825   35.78367 
#> 
#> [[4]]
#>       xmin       ymin       xmax       ymax 
#> -117.85719   35.77998 -117.85272   35.78370 
#> 
#> [[5]]
#>       xmin       ymin       xmax       ymax 
#> -117.85275   35.77629 -117.84827   35.77998 
#> 
#> [[6]]
#>      xmin      ymin      xmax      ymax 
#> -117.8572   35.7763 -117.8527   35.7800

# get section geometries rather than subsections
v2 <- LL2PLSS(p$lon, p$lat, returnlevel = 'S')
plot(v2$geom)
plot(sf::st_as_sf(p, coords = c("lon", "lat"), crs = "OGC:CRS84"), add = TRUE)
```

![](https://i.imgur.com/0WY65fn.png)

``` r
lapply(v2$geom, sf::st_bbox)
#> [[1]]
#>       xmin       ymin       xmax       ymax 
#> -117.88384   35.73976 -117.86600   35.75448 
#> 
#> [[2]]
#>       xmin       ymin       xmax       ymax 
#> -117.86615   35.76894 -117.84825   35.78370 
#> 
#> [[3]]
#>       xmin       ymin       xmax       ymax 
#> -117.86615   35.76894 -117.84825   35.78370 
#> 
#> [[4]]
#>       xmin       ymin       xmax       ymax 
#> -117.86615   35.76894 -117.84825   35.78370 
#> 
#> [[5]]
#>       xmin       ymin       xmax       ymax 
#> -117.86615   35.76894 -117.84825   35.78370 
#> 
#> [[6]]
#>       xmin       ymin       xmax       ymax 
#> -117.86615   35.76894 -117.84825   35.78370
```
