### ISSUE TITLE
{vegan} requires R >= 4.1.0

### ISSUE THREAD

**Issue by brownag** [ncss-tech/sharpshootR#58]
{sharpshootR} has {vegan}, which now requires R >= 4.1.0, in _Imports_ which means that [sharpshootR is no longer installable on R <4.1](https://github.com/ncss-tech/aqp/actions/runs/9277403842/job/25526514702#step:6:165)

Two options:
 - Gate all usage of {vegan} behind `requireNamespace()` and move to _Suggests_
 - Increase minimum R version in _Depends_ for sharpshootR to 4.1.0. 

For the latter option, aqp only has sharpshootR in _Suggests_ so we would not need to increase minimum R version there. 
That said we try to install all suggested packages in the CI --which still includes R 3.6.x. If we take the second route we would want to update GitHub actions to skip install of sharpshootR on older versions of R

**Comment by dylanbeaudette** [comment]
Thanks for spotting this. It looks like all of our packages depend on a rather old version of R.

I'm going to move vegan → suggests in sharpshootR. The only reason I have for keeping compatibility with an older version of R is the old SoilWeb servers. Those will be phased out soon. We can re-visit the minimum R version topic then.

**Comment by brownag** [comment]
I personally don't like the idea of setting a minimum version unless there is a _very_ good reason. So I like the choice of going to Suggests for vegan as it is not critical to functionality of most package functions. The current minimum version 3.5 I believe is related to the serialization methods used for internal package data.

Eventually it would be good to require version >=4 so we never have to think about `stringsAsFactors=TRUE` ever again. 
Using >=4.1 would be nice to be able to use base pipe operator. But I personally am in no rush for either of these. 

Ubuntu 20.04 LTS, which is still under support for next year or so, has [r-base package version 3.6.3-2 in the universe repo](https://packages.ubuntu.com/search?keywords=r-base). Of course it is easy to add additional repositories and use a newer version, but I do think it is worth paying attention to the versions available by default in common linux distributions when making decisions about what version to provide minimum support for.

As far as CRAN goes, they do not check R 3.6 anymore, so this should be a non-issue. No rush on updating for them at least.

**Comment by dylanbeaudette** [comment]
Agreed. I'm in no rush either.
